[project]
name = "bitberet-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.7",
    "django-environ>=0.12.0",
    "django-extensions>=3.2.3",
    "furo>=2024.8.6",
    "gunicorn>=23.0.0",
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "werkzeug>=3.1.3",
]
