# Generated by Django 5.1.7 on 2025-04-07 23:51

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/hyunwoo/Documents/gotchacoins/gotchacoins-dashboard/media/public')), upload_to='avatars/'),
        ),
    ]
