# Generated by Django 5.1.7 on 2025-04-06 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('terms', '이용약관'), ('privacy', '개인정보 처리방침'), ('marketing', '마케팅 수신 동의')], max_length=20)),
                ('agreed', models.BooleanField(default=True)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'agreement_type', 'version')},
            },
        ),
    ]
